# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NuDAS.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(False)
        MainWindow.resize(2000, 1500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidgetSpikes = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetSpikes.setEnabled(False)
        self.listWidgetSpikes.setGeometry(QtCore.QRect(10, 10, 401, 491))
        self.listWidgetSpikes.setObjectName("listWidgetSpikes")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenStimulus = QtWidgets.QAction(MainWindow)
        self.actionOpenStimulus.setObjectName("actionOpenStimulus")
        self.actionOpenSpikes = QtWidgets.QAction(MainWindow)
        self.actionOpenSpikes.setObjectName("actionOpenSpikes")
        self.actionBinning = QtWidgets.QAction(MainWindow)
        self.actionBinning.setObjectName("actionBinning")
        self.actionZ_Score = QtWidgets.QAction(MainWindow)
        self.actionZ_Score.setObjectName("actionZ_Score")
        self.menuFile.addAction(self.actionOpenStimulus)
        self.menuFile.addAction(self.actionOpenSpikes)
        self.menuTools.addAction(self.actionBinning)
        self.menuTools.addAction(self.actionZ_Score)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionOpenStimulus.setText(_translate("MainWindow", "Open Stimulus File"))
        self.actionOpenStimulus.setStatusTip(_translate("MainWindow", "Imports and displays the .mat file containing the trigger stimulus data."))
        self.actionOpenSpikes.setText(_translate("MainWindow", "Open Spikes File"))
        self.actionBinning.setText(_translate("MainWindow", "Binning"))
        self.actionZ_Score.setText(_translate("MainWindow", "Z-Score"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
